- name : Configure Docker on test-server Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name : Updating apt
    command : apt update
  
 - name : install Python
   command : apt install python-pip3 -y
    
  - name : Install Docker
    command :  apt install docker -y
    become : yes
    become_user : ubuntu

  - name : Start Docker Service
    command : systemctl start docker
    become : yes
    become_user : ubuntu

  - name : Run the Bank application
    command: docker run -dt -p 9000:8081 cbabu85/bankingfinance:latest
