- name : Configure Docker on test-server Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name : Updating apt
    command : sudo apt update
  
  - name : install Python
    command : sudo apt install -y python-pip
    
  - name : Install Docker
    command : sudo apt-get install -y docker.io 
    become : yes
    become_user : ubuntu

  - name : Start Docker Service
    command : sudo systemctl start docker 
    become : yes
    become_user : ubuntu

  - name : Run the Bank application
    command: docker run -dt -p 9000:8081 cbabu85/bankingfinance:latest
